version: 2

defaults: &defaults
  working_directory: /tmp/workspace

prototool: &prototool
  <<: *defaults
  docker:
    - image: uber/prototool:1.8.1

docker: &docker
  <<: *defaults
  docker:
    - image: circleci/buildpack-deps:stretch

jobs:
  setup:
    machine: true
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: '*'
  lint:
    <<: *prototool
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Lint
          command: |
            prototool format proto/ -d
  build-go:
    <<: *docker
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Build
          command: |
            ./tool/build-go.sh

workflows:
  version: 2
  build:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build-go:
          requires:
            - lint
