version: 2

defaults: &defaults
  working_directory: /tmp/workspace

prototool: &prototool
  <<: *defaults
  docker:
    - image: uber/prototool:1.8.1

docker: &docker_builder
  <<: *defaults
  machine:
    image: circleci/classic:201703-01

jobs:
  setup:
    machine: true
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: '*'
  lint:
    <<: *prototool
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Lint
          command: |
            prototool format proto/ -d
  build-go:
    <<: *docker_builder
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Build
          command: |
            make build-go
  push-go:
    <<: *docker_builder
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Build
          command: |
            make push-go

workflows:
  version: 2
  build:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build-go:
          requires:
            - lint
